version: "3.9"
services:
  front:
    build:
      # frontディレクトリのDockerfileを参照
      context: ./front/ 
      dockerfile: Dockerfile
    volumes:
      # ./frontを/usr/src/appにマウント 
      - ./front:/usr/src/app
    command: >
      bash -c "npm install && npm run dev"
    ports:
      - "7001:3000"

  api:
    tty: true
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      # ホストのポート4001を使用
      - "4001:3000"  
    volumes:
      - ./api:/app
      # Gemファイルを更新した場合、ホスト側でbundle installを実行する
      - bundle:/usr/local/bundle
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db

  db:
    image: postgres:15.3
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "30002:3306"
    environment:
      POSTGRES_DB: 'questory_local'
      POSTGRES_USER: 'questory_local'
      POSTGRES_PASSWORD: 'password'
      TZ: "Asia/Tokyo"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"

volumes:
  bundle:
  postgres: